### ISSUE TITLE
Post images

### ISSUE THREAD

**Issue by ghost** [hvy/chainer-wasserstein-gan#1]
Hi, 

thanks for sharing your code, looks really neat! I'm trying to do a lasagne implementation of your code and I was hoping you could post pictures of the images you got, so I can compare with mine. Thanks!

**Comment by hvy** [comment]
Hi and sure. 

These are images from epoch 10, 100 and 200 training with CIFAR-10. 
All inputs to the generator are randomly sampled each time.

![10](https://cloud.githubusercontent.com/assets/5983694/24243270/e27decbc-0ffd-11e7-8f1e-1da8955c977b.png)
![100](https://cloud.githubusercontent.com/assets/5983694/24243271/e27ff890-0ffd-11e7-95eb-e05a1f3e76f3.png)
![200](https://cloud.githubusercontent.com/assets/5983694/24244273/83f35606-1001-11e7-9cea-0ee511983192.png)

**Comment by ghost** [comment]
Awesome! Thanks
